### ISSUE TITLE
Rendering a typed link field breaks front-end debug toolbar

### ISSUE THREAD

**Issue by Antimated** [sebastian-lenz/craft-linkfield#244] opened 2022-11-09 10:36 UTC
Trying to render a basic typed link field on the front-end with the following code will break the tabs of the front-end debug toolbar. PHP errors are being thrown...

```twig
{% if not entry.linkIt.isEmpty() %}
    {{ entry.linkIt.getLink() }}
{% endif %}
```

### Errors
This outputs the following errors (error seems to be different for the request tab):

#### Request tab
![Screenshot 2022-11-09 at 11 26 26](https://user-images.githubusercontent.com/2869409/200805984-2712ae69-03e9-4c3e-8503-369b1cf37784.png)

#### Other tabs (DB in this instance)
![Screenshot 2022-11-09 at 11 26 39](https://user-images.githubusercontent.com/2869409/200806048-f3267a4c-74ef-4d3d-b8f7-b2b8f4818e63.png)

###  Plugin version
- Typed link field: 2.1.4

### Relevant information
- PHP version: 8.1.5
- OS version: Darwin 20.5.0
- Database driver & version: MySQL 5.7.34
- Yii version: 2.0.46
- Craft edition & version: Craft Pro 4.3.1

**Comment by jessedobbelaere** [comment] 2022-11-13 13:32
I can reproduce that error with the craft-linkfield plugin 👍 This issue brought me here https://github.com/craftcms/cms/issues/12010#issuecomment-1271225724

**Comment by sebastian-lenz** [comment] 2022-11-29 09:20
Duplicate of #152

**Closed by sebastian-lenz** 2022-11-29 09:20 UTC
