### ISSUE TITLE
Craft 4 - RC1: SQL Error

### ISSUE THREAD

**Issue by mihob** [sebastian-lenz/craft-linkfield#217] opened 2022-04-28 00:24 UTC
When trying to create a new entry that contains a linkfield i get the following error:

```
{
    "error": "SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`project`.`lenz_linkfield`, CONSTRAINT `fk_hcnpdsfuimkvgdhthgqgqiqkhmrloeuermge` FOREIGN KEY (`linkedId`) REFERENCES `elements` (`id`) ON DELETE SET NULL ON UPDATE SET NULL)\nThe SQL being executed was: INSERT INTO `lenz_linkfield` (`elementId`, `fieldId`, `siteId`, `linkedId`, `linkedSiteId`, `linkedTitle`, `linkedUrl`, `payload`, `type`, `dateCreated`, `dateUpdated`, `uid`) VALUES (39, 2, 1, 0, NULL, NULL, NULL, '[]', 'entry', '2022-04-28 00:21:46', '2022-04-28 00:21:46', 'c3ee722b-d52e-4710-9617-e99c5fc076dd')",
    "exception": "yii\\db\\IntegrityException",
    "file": "/app/vendor/yiisoft/yii2/db/Schema.php",
    "line": 676,
    "trace": [
        {
            "file": "/app/vendor/yiisoft/yii2/db/Command.php",
            "line": 1307,
            "function": "convertException",
            "class": "yii\\db\\Schema",
            "type": "->"
        },
        {
            "file": "/app/vendor/yiisoft/yii2/db/Command.php",
            "line": 1102,
            "function": "internalExecute",
            "class": "yii\\db\\Command",
            "type": "->"
        },
        {
            "file": "/app/vendor/yiisoft/yii2/db/Schema.php",
            "line": 431,
            "function": "execute",
            "class": "yii\\db\\Command",
            "type": "->"
        },
        {
            "file": "/app/vendor/yiisoft/yii2/db/ActiveRecord.php",
            "line": 604,
            "function": "insert",
            "class": "yii\\db\\Schema",
            "type": "->"
        },
        {
            "file": "/app/vendor/yiisoft/yii2/db/ActiveRecord.php",
            "line": 570,
            "function": "insertInternal",
            "class": "yii\\db\\ActiveRecord",
            "type": "->"
        },
        {
            "file": "/app/vendor/yiisoft/yii2/db/BaseActiveRecord.php",
            "line": 676,
            "function": "insert",
            "class": "yii\\db\\ActiveRecord",
            "type": "->"
        },
        {
            "file": "/app/vendor/sebastianlenz/craft-utils/src/foreignField/ForeignField.php",
            "line": 46,
            "function": "save",
            "class": "yii\\db\\BaseActiveRecord",
            "type": "->"
        },
        {
            "file": "/app/vendor/craftcms/cms/src/base/Element.php",
            "line": 4512,
            "function": "afterElementSave",
            "class": "lenz\\craft\\utils\\foreignField\\ForeignField",
            "type": "->"
        },
        {
            "file": "/app/vendor/craftcms/cms/src/elements/Entry.php",
            "line": 1964,
            "function": "afterSave",
            "class": "craft\\base\\Element",
            "type": "->"
        },
        {
            "file": "/app/vendor/craftcms/cms/src/services/Elements.php",
            "line": 2713,
            "function": "afterSave",
            "class": "craft\\elements\\Entry",
            "type": "->"
        },
        {
            "file": "/app/vendor/craftcms/cms/src/services/Elements.php",
            "line": 788,
            "function": "_saveElementInternal",
            "class": "craft\\services\\Elements",
            "type": "->"
        },
        {
            "file": "/app/vendor/craftcms/cms/src/services/Drafts.php",
            "line": 244,
            "function": "saveElement",
            "class": "craft\\services\\Elements",
            "type": "->"
        },
        {
            "file": "/app/vendor/craftcms/cms/src/controllers/EntriesController.php",
            "line": 168,
            "function": "saveElementAsDraft",
            "class": "craft\\services\\Drafts",
            "type": "->"
        },
        {
            "function": "actionCreate",
            "class": "craft\\controllers\\EntriesController",
            "type": "->"
        },
        {
            "file": "/app/vendor/yiisoft/yii2/base/InlineAction.php",
            "line": 57,
            "function": "call_user_func_array"
        },
        {
            "file": "/app/vendor/yiisoft/yii2/base/Controller.php",
            "line": 178,
            "function": "runWithParams",
            "class": "yii\\base\\InlineAction",
            "type": "->"
        },
        {
            "file": "/app/vendor/yiisoft/yii2/base/Module.php",
            "line": 552,
            "function": "runAction",
            "class": "yii\\base\\Controller",
            "type": "->"
        },
        {
            "file": "/app/vendor/craftcms/cms/src/web/Application.php",
            "line": 301,
            "function": "runAction",
            "class": "yii\\base\\Module",
            "type": "->"
        },
        {
            "file": "/app/vendor/craftcms/cms/src/web/Application.php",
            "line": 625,
            "function": "runAction",
            "class": "craft\\web\\Application",
            "type": "->"
        },
        {
            "file": "/app/vendor/craftcms/cms/src/web/Application.php",
            "line": 280,
            "function": "_processActionRequest",
            "class": "craft\\web\\Application",
            "type": "->"
        },
        {
            "file": "/app/vendor/yiisoft/yii2/base/Application.php",
            "line": 384,
            "function": "handleRequest",
            "class": "craft\\web\\Application",
            "type": "->"
        },
        {
            "file": "/app/web/index.php",
            "line": 12,
            "function": "run",
            "class": "yii\\base\\Application",
            "type": "->"
        }
    ]
}
```

**Comment by sebastian-lenz** [comment] 2022-05-08 13:05
This seems to be a duplicate of #219. I can not reproduce this on my side and I currently assume that Craft 4 exposes problems due to missing element records. What did you do exactly when this error was thrown? Did you try to save the new entry or was it before? Where is the link field located (on the entry or e.g. within a matrix field) and what value did oyu set it to?

**Comment by sebastian-lenz** [comment] 2022-05-09 08:34
Okay, I think I've found the bug, it's related to the way Craft now handles newly created elements. Please refer to #219 for any further discussion.

**Closed by sebastian-lenz** 2022-05-09 08:34 UTC
Labels: duplicate
