### ISSUE TITLE
Beta 12 - Can't save entity if I have required field even in disabled block

### ISSUE THREAD

**Issue by startusin** [sebastian-lenz/craft-linkfield#145] opened 2021-03-01 10:26 UTC
Hi there!

Found one issue, related to saving an entity.
I can't save entity if I have required field even in disabled block.
Hope that it will be helpful for development at all. 
Thank you!

**Comment by sebastian-lenz** [comment] 2021-03-01 20:19
Hi @startusin, thanks for getting in touch. With "disabled block" I guess you mean an entry within a matrix block field which has been disabled? If so, that's the expected behaviour. Just because a block is disabled does not mean it's fields do not get validated. Craft will ensure all required fields are filled out, no matter whether the block is enabled or disabled.

**Comment by sebastian-lenz** [comment] 2021-03-23 19:19
I'll close this issue has I didn't hear back from you.

**Closed by sebastian-lenz** 2021-03-23 19:19 UTC
Labels: question
