### ISSUE TITLE
Craft 3.3 GraphQL returns String only

### ISSUE THREAD

**Issue by djurdjen** [sebastian-lenz/craft-linkfield#75] opened 2019-09-17 07:42 UTC
Hello! First of all, thanks for the great plugin! 
I experience an issue with GraphQL in Craft 3.3 when trying to return a linkfield. The Schema doesn't seem to be up to date as the output is of type `String`.

craft-linkfield: 2.0.0-beta.6
craft: 3.3.3

**Comment by sebastian-lenz** [comment] 2019-09-23 14:55
Hm, I don't see no problem here, in my test case Craft returns an object type for link fields. Could you give additional details on how to reproduce the problem?

**Comment by dangayle** [comment] 2019-10-02 23:24
Here's a screenshot of my GraphiQL editor:
<img width="1058" alt="Screen Shot 2019-10-02 at 4 24 01 PM" src="https://user-images.githubusercontent.com/129611/66088760-192c4280-e531-11e9-9beb-0b136e82981e.png">

**Comment by Toni-hr98** [comment] 2019-10-03 08:02
It works with the CraftQL plugin, but it doesn't work in the new graphQL plugin that came with the craft update 3.3.0

**Comment by sebastian-lenz** [comment] 2019-10-07 08:08
This plugin supports CraftQL on the 1.x branch and has native GraphQL support on the 2.x branch. The original issue was about the 2.x branch.

@dangayle If you are using the 1.x version of the plugin, this behavior is as expected.

**Comment by dangayle** [comment] 2019-10-07 15:27
Oh, let me swap that out then! Thank you.

**Comment by sebastian-lenz** [comment] 2019-10-08 07:59
@dangayle The 2.x version is a big backup, please create a backup of your database before running the backup. Also, should you encounter any problems, please report them.

**Comment by Toni-hr98** [comment] 2019-10-15 09:42
@sebastian-lenz the option: (Open in new window?) doesn't work..

**Comment by sebastian-lenz** [comment] 2019-10-21 15:54
@Toni-hr98 Yeah, the GraphQL was missing the `target` field, it will be included in the next release, please see #80

**Comment by sebastian-lenz** [comment] 2020-06-08 20:17
I'll close this one due to inactivity. Please feel free to open a new issue should there be any problems left.

**Closed by sebastian-lenz** 2020-06-08 20:17 UTC
Labels: question
