### ISSUE TITLE
Allow making custom text translatable while entry/categories are not translatable

### ISSUE THREAD

**Issue by piotrpog** [sebastian-lenz/craft-linkfield#92] opened 2020-02-13 12:07 UTC
I would like to keep linking to same entry on all languages, while making custom link text translatable.

 Currently either we translate all sub-fields of link field or none of them.

**Comment by sebastian-lenz** [comment] 2020-02-14 11:03
This is a duplicate of #48. The problem is that you want to translate a part of the link field. While I see the point (and need) for this, this is cannot be explained with the translation behavior of Craft fields.

Create an untranslated link field and as translated text field and use the translated text field as the label for your links.

**Closed by sebastian-lenz** 2020-02-14 11:03 UTC
